import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { ApiError, api } from "../../shared/api";
import type { Booking, ExtraCharge, Invoice, Payment } from "../../domain/types";

function BillingPanel() {
  const [items, setItems] = useState<Booking[]>([]); const [selected, setSelected] = useState<Booking | null>(null); const [invoice, setInvoice] = useState<Invoice>(null); const [payments, setPayments] = useState<Payment[]>([]); const [charges, setCharges] = useState<ExtraCharge[]>([]); const [charge, setCharge] = useState({ description: "", amount: "" }); const [payment, setPayment] = useState({ amount: "", method: "CASH", reference: "", note: "" }); const [error, setError] = useState(""); const [submittingPayment, setSubmittingPayment] = useState(false); const [paymentOperationToken, setPaymentOperationToken] = useState<string | null>(null);
  async function refresh(id?: string) { try { const next = await api<Booking[]>("/bookings?limit=100"); setItems(next); const current = next.find(item => item.id === id) ?? selected ?? next[0]; if (!current) return; setSelected(current); const [i, p, x] = await Promise.all([api<Invoice>(`/bookings/${current.id}/invoice`), api<Payment[]>(`/bookings/${current.id}/payments`), api<ExtraCharge[]>(`/bookings/${current.id}/extra-charges`)]); setInvoice(i); setPayments(p); setCharges(x); } catch (e) { setError((e as Error).message); } }
  useEffect(() => { void refresh(); }, []);
  async function submitCharge(event: FormEvent) { event.preventDefault(); if (!selected) return; try { await api(`/bookings/${selected.id}/extra-charges`, { method: "POST", body: JSON.stringify({ description: charge.description, amount_cents: Number(charge.amount), category: "OTHER" }) }); setCharge({ description: "", amount: "" }); await refresh(selected.id); } catch (e) { setError((e as Error).message); } }
  async function submitPayment(event: FormEvent) { event.preventDefault(); if (!selected || submittingPayment) return; setError(""); setSubmittingPayment(true); const operationToken = paymentOperationToken ?? crypto.randomUUID(); setPaymentOperationToken(operationToken); try { await api(`/bookings/${selected.id}/payments`, { method: "POST", body: JSON.stringify({ amount_cents: Number(payment.amount), payment_method: payment.method, payment_reference: payment.reference || undefined, note: payment.note || undefined, operation_token: operationToken }) }); setPayment({ ...payment, amount: "", reference: "", note: "" }); setPaymentOperationToken(null); await refresh(selected.id); } catch (e) { const apiError = e instanceof ApiError ? e : null; await refresh(selected.id); if (apiError && apiError.status >= 400 && apiError.status < 500) { setPaymentOperationToken(null); setError(apiError.message); } else { setError(`${(e as Error).message}. Se actualizó el saldo; verificá el estado antes de reintentar.`); } } finally { setSubmittingPayment(false); } }
  return <section className="billing-workspace"><div className="workspace-heading"><div><p className="eyebrow">Finance</p><h2>Billing and payments</h2><p className="muted">Exact cents, payment history and booking invoice</p></div></div>{error && <p className="error" role="alert">{error}</p>}<label>Booking <select aria-label="Billing booking" value={selected?.id ?? ""} onChange={e => void refresh(e.target.value)}><option value="">Select booking</option>{items.map(item => <option key={item.id} value={item.id}>{item.guest_name} · {item.room_number}</option>)}</select></label>{selected && <article className="case-panel"><h3>{selected.guest_name} · Invoice</h3><p className="muted">Total {invoice?.amount_cents ?? selected.total_cents} cents · Paid {invoice?.paid_amount_cents ?? 0} cents · Remaining {Math.max(0, (invoice?.amount_cents ?? selected.total_cents) - (invoice?.paid_amount_cents ?? 0))} cents · {invoice?.status ?? "PENDING"}</p><form onSubmit={submitCharge} aria-label="Billing extra charge"><input required aria-label="Billing charge description" placeholder="Description" value={charge.description} onChange={e => setCharge({ ...charge, description: e.target.value })} /><input required min="1" type="number" aria-label="Billing charge amount" placeholder="Amount cents" value={charge.amount} onChange={e => setCharge({ ...charge, amount: e.target.value })} /><button>Add extra charge</button></form><form onSubmit={submitPayment} aria-label="Billing payment"><input required min="1" type="number" aria-label="Billing payment amount" placeholder="Payment cents" value={payment.amount} onChange={e => setPayment({ ...payment, amount: e.target.value })} /><select aria-label="Billing payment method" value={payment.method} onChange={e => setPayment({ ...payment, method: e.target.value })}><option value="CASH">Cash</option><option value="CARD">Card</option><option value="TRANSFER">Transfer</option></select><input aria-label="Billing payment reference" placeholder="Reference" value={payment.reference} onChange={e => setPayment({ ...payment, reference: e.target.value })} /><input aria-label="Billing payment note" placeholder="Note" value={payment.note} onChange={e => setPayment({ ...payment, note: e.target.value })} /><button type="submit" disabled={submittingPayment}>{submittingPayment ? "Registering…" : "Register payment"}</button></form>{charges.map(item => <p className="muted" key={item.id}>Charge · {item.description} · {item.amount_cents} cents</p>)}{payments.map(item => <p className="muted" key={item.id}>Payment · {item.amount_cents} cents · {item.payment_method}</p>)}</article>}</section>;
}

type CashBalance = { total_amount_cents: number; cash_amount_cents: number; card_amount_cents: number; non_cash_amount_cents: number; payment_count: number; pending_amount_cents: number; opening_time: string };
function CashBalancePanel() {
  const [balance, setBalance] = useState<CashBalance | null>(null); const [counted, setCounted] = useState(""); const [handoff, setHandoff] = useState(""); const [notes, setNotes] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function refresh() { try { setBalance(await api<CashBalance>("/billing/balance")); } catch (e) { setError((e as Error).message); } }
  useEffect(() => { void refresh(); }, []);
  async function closeShift(event: FormEvent) { event.preventDefault(); if (!balance) return; setError(""); setMessage(""); try { const result = await api<{ cash_difference_cents: number }>("/billing/close-cash", { method: "POST", body: JSON.stringify({ expected_cash_amount_cents: balance.cash_amount_cents, expected_total_amount_cents: balance.total_amount_cents, expected_non_cash_amount_cents: balance.non_cash_amount_cents, expected_payment_count: balance.payment_count, counted_cash_amount_cents: Number(counted), handoff_to: handoff, notes: notes || undefined }) }); setMessage(`Shift closed · difference ${result.cash_difference_cents} cents`); setCounted(""); setHandoff(""); setNotes(""); await refresh(); } catch (e) { setError((e as Error).message); await refresh(); } }
  return <section className="billing-workspace" aria-label="Cash balance and close"><div className="workspace-heading"><div><p className="eyebrow">Cash operations</p><h2>Current shift balance</h2><p className="muted">Revalidated at close; handoff remains auditable</p></div><button type="button" onClick={() => void refresh()}>Refresh balance</button></div>{error && <p className="error" role="alert">{error}</p>}{message && <p className="status-badge" role="status">{message}</p>}{balance && <><div className="cards"><article><strong>Total {balance.total_amount_cents} cents</strong><span>Cash {balance.cash_amount_cents} cents</span><span>Non-cash {balance.non_cash_amount_cents} cents</span><span>{balance.payment_count} payments</span></article><article><span>Pending invoices {balance.pending_amount_cents} cents</span><span>Opening {balance.opening_time}</span></article></div><form onSubmit={closeShift} aria-label="Close cash shift"><label>Expected cash <input aria-label="Expected cash cents" type="number" value={balance.cash_amount_cents} readOnly /></label><label>Counted cash <input required min="0" aria-label="Counted cash cents" type="number" value={counted} onChange={e => setCounted(e.target.value)} /></label><label>Handoff to <input required minLength={1} aria-label="Handoff to" value={handoff} onChange={e => setHandoff(e.target.value)} /></label><label>Notes <input aria-label="Close notes" value={notes} onChange={e => setNotes(e.target.value)} /></label><button>Close cash shift</button></form></>}</section>;
}

export function BillingWorkspace() {
  return <><BillingPanel /><CashBalancePanel /></>;
}
