import { useEffect, useState } from "react";
import { api } from "../../shared/api";

type ReportRange = { start: string; end: string };
export function ReportsPage() {
  const [range, setRange] = useState<ReportRange>({ start: "2026-09-01", end: "2026-10-01" }); const [revenue, setRevenue] = useState<Array<{ date: string; revenue_cents: number }> | null>(null); const [occupancy, setOccupancy] = useState<Array<{ date: string; occupied_rooms: number; total_rooms: number; occupancy_rate: number }> | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function load() { setLoading(true); setError(""); try { const query = `start=${range.start}&end=${range.end}`; const [r, o] = await Promise.all([api<typeof revenue>(`/reports/revenue?${query}`), api<typeof occupancy>(`/reports/occupancy?${query}`)]); setRevenue(r); setOccupancy(o); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  const totalRevenue = revenue?.reduce((sum, row) => sum + row.revenue_cents, 0) ?? 0; const totalOccupied = occupancy?.reduce((sum, row) => sum + row.occupied_rooms, 0) ?? 0;
  return <section className="admin-surface"><div className="workspace-heading"><div><p className="eyebrow">Analytics</p><h2>Reports</h2><p className="muted">Source-equivalent daily revenue and occupancy series</p></div><span className="case-count">{occupancy?.length ?? 0} days</span></div><div className="report-controls"><div className="date-range"><label>Start <input aria-label="Report start" type="date" value={range.start} onChange={e => setRange({ ...range, start: e.target.value })} /></label><label>End <input aria-label="Report end" type="date" value={range.end} onChange={e => setRange({ ...range, end: e.target.value })} /></label></div><button type="button" onClick={() => void load()} disabled={loading}>{loading ? "Loading…" : "Refresh report"}</button></div>{error && <div className="error-row"><p className="error" role="alert">{error}</p><button type="button" onClick={() => void load()}>Retry</button></div>}{loading && !occupancy ? <p className="muted loading-state" role="status">Loading reports…</p> : occupancy && revenue ? <>{occupancy.length === 0 && revenue.length === 0 ? <div className="empty-state"><h3>No report data in this range</h3><p className="muted">Choose another date range and refresh the report.</p></div> : <><div className="kpi-grid"><article><strong>Revenue</strong><span>${(totalRevenue / 100).toFixed(2)}</span></article><article><strong>Occupancy days</strong><span>{occupancy.length}</span></article><article><strong>Occupied rooms</strong><span>{totalOccupied}</span></article><article><strong>Rooms/day</strong><span>{occupancy[0]?.total_rooms ?? 0}</span></article></div><div className="report-grid"><div className="cards"><h3>Revenue by arrival date</h3>{revenue.length === 0 && <p className="muted">No revenue in this range.</p>}{revenue.map(row => <article key={row.date}><strong>{row.date}</strong><span>${(row.revenue_cents / 100).toFixed(2)}</span></article>)}</div><div className="cards"><h3>Daily occupancy</h3>{occupancy.length === 0 && <p className="muted">No occupancy in this range.</p>}{occupancy.map(row => <article key={row.date}><strong>{row.date}</strong><span>{row.occupied_rooms}/{row.total_rooms} · {row.occupancy_rate.toFixed(2)}%</span></article>)}</div></div></>}</> : null}</section>;
}
