import { useEffect, useState } from "react";
import { api } from "../../api/client";
import { useI18n } from "../../i18n";

type ReportRange = { start: string; end: string };
export function ReportsPage() {
  const { t, formatCurrency, formatDate, formatPercent } = useI18n();
  const [range, setRange] = useState<ReportRange>({ start: "2026-09-01", end: "2026-10-01" }); const [revenue, setRevenue] = useState<Array<{ date: string; revenue_cents: number }> | null>(null); const [occupancy, setOccupancy] = useState<Array<{ date: string; occupied_rooms: number; total_rooms: number; occupancy_rate: number }> | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function load() { setLoading(true); setError(""); try { const query = `start=${range.start}&end=${range.end}`; const [r, o] = await Promise.all([api<typeof revenue>(`/reports/revenue?${query}`), api<typeof occupancy>(`/reports/occupancy?${query}`)]); setRevenue(r); setOccupancy(o); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  const totalRevenue = revenue?.reduce((sum, row) => sum + row.revenue_cents, 0) ?? 0; const totalOccupied = occupancy?.reduce((sum, row) => sum + row.occupied_rooms, 0) ?? 0;
  return <section className="admin-surface"><div className="workspace-heading"><div><p className="eyebrow">{t("reports.analytics")}</p><h2>{t("reports.title")}</h2><p className="muted">{t("reports.subtitle")}</p></div><span className="case-count">{t("reports.days", { count: occupancy?.length ?? 0 })}</span></div><div className="report-controls"><div className="date-range"><label>{t("common.start")} <input aria-label={t("reports.startAria")} type="date" value={range.start} onChange={e => setRange({ ...range, start: e.target.value })} /></label><label>{t("common.end")} <input aria-label={t("reports.endAria")} type="date" value={range.end} onChange={e => setRange({ ...range, end: e.target.value })} /></label></div><button type="button" onClick={() => void load()} disabled={loading}>{loading ? t("reports.loading") : t("reports.refresh")}</button></div>{error && <div className="error-row"><p className="error" role="alert">{error}</p><button type="button" onClick={() => void load()}>{t("reports.retry")}</button></div>}{loading && !occupancy ? <p className="muted loading-state" role="status">{t("reports.loadingReports")}</p> : occupancy && revenue ? <>{occupancy.length === 0 && revenue.length === 0 ? <div className="empty-state"><h3>{t("reports.noData")}</h3><p className="muted">{t("reports.noDataHint")}</p></div> : <><div className="kpi-grid"><article><strong>{t("reports.revenue")}</strong><span>{formatCurrency(totalRevenue)}</span></article><article><strong>{t("reports.occupancyDays")}</strong><span>{occupancy.length}</span></article><article><strong>{t("reports.occupiedRooms")}</strong><span>{totalOccupied}</span></article><article><strong>{t("reports.roomsPerDay")}</strong><span>{occupancy[0]?.total_rooms ?? 0}</span></article></div><div className="report-grid"><div className="cards"><h3>{t("reports.revenueByArrival")}</h3>{revenue.length === 0 && <p className="muted">{t("reports.noRevenue")}</p>}{revenue.map(row => <article key={row.date}><strong>{formatDate(row.date)}</strong><span>{formatCurrency(row.revenue_cents)}</span></article>)}</div><div className="cards"><h3>{t("reports.dailyOccupancy")}</h3>{occupancy.length === 0 && <p className="muted">{t("reports.noOccupancy")}</p>}{occupancy.map(row => <article key={row.date}><strong>{formatDate(row.date)}</strong><span>{row.occupied_rooms}/{row.total_rooms} · {formatPercent(row.occupancy_rate)}</span></article>)}</div></div></>}</> : null}</section>;
}
