import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { api } from "../../api/client";
import { useI18n } from "../../i18n";

type AdminHotel = { id: string; slug: string; name: string; address: string | null; plan_tier: string; operational_binding: string; active: number };
type NetworkKpis = { total_hotels: number; total_active_bookings: number; total_revenue_cents: number; average_occupancy_rate: number; hotels: Array<{ hotel_id: string; hotel_name: string; plan_tier: string; revenue_cents: number; active_bookings_count: number; occupancy_rate: number; adr_cents: number; rev_par_cents: number }> };

export function NetworkPage() {
  const { t, planLabel, formatCurrency, formatPercent } = useI18n();
  const [hotels, setHotels] = useState<AdminHotel[]>([]); const [selected, setSelected] = useState<AdminHotel | null>(null); const [kpis, setKpis] = useState<NetworkKpis | null>(null); const [search, setSearch] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [form, setForm] = useState({ id: "", slug: "", name: "", operational_binding: "HOTEL_SECOND_DB", plan_tier: "BASIC" }); const [range, setRange] = useState({ start: "2026-09-01", end: "2026-10-01" });
  async function load() { setLoading(true); setError(""); try { setHotels(await api<AdminHotel[]>("/hotels")); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  async function loadKpis() { setError(""); try { setKpis(await api<NetworkKpis>(`/hotels/network-kpis?start=${range.start}&end=${range.end}`)); } catch (e) { setError((e as Error).message); } }
  useEffect(() => { void load(); void loadKpis(); }, []);
  async function register(event: FormEvent) { event.preventDefault(); setError(""); setMessage(""); try { await api("/hotels", { method: "POST", body: JSON.stringify(form) }); setMessage(t("network.propertyRegistered")); setForm({ id: "", slug: "", name: "", operational_binding: "HOTEL_SECOND_DB", plan_tier: "BASIC" }); await load(); await loadKpis(); } catch (e) { setError((e as Error).message); } }
  async function updatePlan(plan_tier: string) { if (!selected) return; const authoritative = hotels.find(h => h.id === selected.id) ?? selected; setError(""); setMessage(""); try { await api(`/hotels/${selected.id}/plan`, { method: "PATCH", body: JSON.stringify({ plan_tier }) }); setMessage(t("network.planUpdated")); await load(); await loadKpis(); } catch (e) { setSelected(authoritative); setError((e as Error).message); } }
  const visible = hotels.filter(h => `${h.name} ${h.slug} ${h.id}`.toLowerCase().includes(search.toLowerCase())); const usedBindings = new Set(hotels.map(h => h.operational_binding));
  return <section className="admin-surface"><div className="workspace-heading"><div><p className="eyebrow">{t("network.eyebrow")}</p><h2>{t("network.title")}</h2><p className="muted">{t("network.subtitle")}</p></div><span className="case-count">{t("network.properties", { count: hotels.length })}</span></div>
    <form className="admin-create" onSubmit={register}><h3>{t("network.registerProperty")}</h3><div className="form-field"><label htmlFor="hotel-id">{t("network.propertyId")}</label><input id="hotel-id" required placeholder={t("network.propertyId")} value={form.id} onChange={e => setForm({ ...form, id: e.target.value })} /></div><div className="form-field"><label htmlFor="hotel-slug">{t("network.slug")}</label><input id="hotel-slug" required placeholder={t("network.slug")} value={form.slug} onChange={e => setForm({ ...form, slug: e.target.value })} /></div><div className="form-field"><label htmlFor="hotel-name">{t("network.name")}</label><input id="hotel-name" required placeholder={t("network.name")} value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></div><div className="form-field"><label htmlFor="hotel-binding">{t("network.binding")}</label><select id="hotel-binding" value={form.operational_binding} onChange={e => setForm({ ...form, operational_binding: e.target.value })}><option disabled={usedBindings.has("HOTEL_DEMO_DB")}>HOTEL_DEMO_DB{usedBindings.has("HOTEL_DEMO_DB") ? ` (${t("common.assigned")})` : ""}</option><option disabled={usedBindings.has("HOTEL_SECOND_DB")}>HOTEL_SECOND_DB{usedBindings.has("HOTEL_SECOND_DB") ? ` (${t("common.assigned")})` : ""}</option></select></div><button type="submit" disabled={usedBindings.size >= 2}>{t("network.register")}</button></form>
    <div className="report-controls"><div className="date-range"><label>{t("common.start")} <input aria-label={t("network.reportStartAria")} type="date" value={range.start} onChange={e => setRange({ ...range, start: e.target.value })} /></label><label>{t("common.end")} <input aria-label={t("network.reportEndAria")} type="date" value={range.end} onChange={e => setRange({ ...range, end: e.target.value })} /></label></div><button type="button" onClick={() => void loadKpis()}>{t("network.refreshAnalytics")}</button></div>
    {message && <p className="success" role="status">{message}</p>}{error && <div className="error-row"><p className="error" role="alert">{error}</p><button type="button" onClick={() => { void load(); void loadKpis(); }}>{t("network.retry")}</button></div>}
    {loading ? <p className="muted loading-state" role="status">{t("network.loading")}</p> : <><div className="kpi-grid">{kpis ? <><article><strong>{t("network.totalHotels")}</strong><span>{kpis.total_hotels}</span></article><article><strong>{t("network.revenue")}</strong><span>{formatCurrency(kpis.total_revenue_cents)}</span></article><article><strong>{t("network.activeBookings")}</strong><span>{kpis.total_active_bookings}</span></article><article><strong>{t("network.occupancy")}</strong><span>{formatPercent(kpis.average_occupancy_rate)}</span></article></> : <p className="muted">{t("network.analyticsUnavailable")}</p>}</div>
    <label className="admin-search">{t("network.filter")} <input aria-label={t("network.filter")} value={search} onChange={e => setSearch(e.target.value)} placeholder={t("network.filterPlaceholder")} /></label>{visible.length === 0 ? <div className="empty-state"><h3>{t(hotels.length ? "network.noMatch" : "network.none")}</h3><p className="muted">{t("network.adjust")}</p></div> : <div className="admin-network-layout"><div className="cards">{visible.map(h => <button type="button" className={selected?.id === h.id ? "network-row selected" : "network-row"} key={h.id} onClick={() => setSelected(h)}><strong>{h.name || h.slug}</strong><span>{h.slug} · {h.operational_binding}</span><small>{planLabel(h.plan_tier)}</small></button>)}</div>{selected && <article className="network-detail"><p className="eyebrow">{t("network.propertyDetail")}</p><h3>{selected.name || selected.slug}</h3><p>{selected.address || t("common.noAddress")}</p><label>{t("network.plan")} <select aria-label={t("network.propertyPlanAria")} value={selected.plan_tier} onChange={e => { setSelected({ ...selected, plan_tier: e.target.value }); void updatePlan(e.target.value); }}><option value="BASIC">{planLabel("BASIC")}</option><option value="PRO">{planLabel("PRO")}</option><option value="ENTERPRISE">{planLabel("ENTERPRISE")}</option></select></label>{kpis?.hotels.find(row => row.hotel_id === selected.id) && <p>{t("network.revenue")} {formatCurrency(kpis.hotels.find(row => row.hotel_id === selected.id)!.revenue_cents)} · ADR {formatCurrency(kpis.hotels.find(row => row.hotel_id === selected.id)!.adr_cents)} · RevPAR {formatCurrency(kpis.hotels.find(row => row.hotel_id === selected.id)!.rev_par_cents)}</p>}<button type="button" className="button-secondary" onClick={() => setSelected(null)}>{t("network.closeProperty")}</button></article>}</div>}{kpis && <div className="cards revenue-ranking"><h3>{t("network.revenueRanking")}</h3>{kpis.hotels.map(row => <article key={row.hotel_id}><strong>{row.hotel_name}</strong><span>{formatCurrency(row.revenue_cents)} · {formatPercent(row.occupancy_rate)}</span></article>)}</div>}</>}</section>;
}
