import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { api } from "../../api/client";

type AdminHotel = { id: string; slug: string; name: string; address: string | null; plan_tier: string; operational_binding: string; active: number };
type NetworkKpis = { total_hotels: number; total_active_bookings: number; total_revenue_cents: number; average_occupancy_rate: number; hotels: Array<{ hotel_id: string; hotel_name: string; plan_tier: string; revenue_cents: number; active_bookings_count: number; occupancy_rate: number; adr_cents: number; rev_par_cents: number }> };

export function NetworkPage() {
  const [hotels, setHotels] = useState<AdminHotel[]>([]); const [selected, setSelected] = useState<AdminHotel | null>(null); const [kpis, setKpis] = useState<NetworkKpis | null>(null); const [search, setSearch] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [form, setForm] = useState({ id: "", slug: "", name: "", operational_binding: "HOTEL_SECOND_DB", plan_tier: "BASIC" }); const [range, setRange] = useState({ start: "2026-09-01", end: "2026-10-01" });
  async function load() { setLoading(true); setError(""); try { setHotels(await api<AdminHotel[]>("/hotels")); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  async function loadKpis() { setError(""); try { setKpis(await api<NetworkKpis>(`/hotels/network-kpis?start=${range.start}&end=${range.end}`)); } catch (e) { setError((e as Error).message); } }
  useEffect(() => { void load(); void loadKpis(); }, []);
  async function register(event: FormEvent) { event.preventDefault(); setError(""); setMessage(""); try { await api("/hotels", { method: "POST", body: JSON.stringify(form) }); setMessage("Property registered"); setForm({ id: "", slug: "", name: "", operational_binding: "HOTEL_SECOND_DB", plan_tier: "BASIC" }); await load(); await loadKpis(); } catch (e) { setError((e as Error).message); } }
  async function updatePlan(plan_tier: string) { if (!selected) return; const authoritative = hotels.find(h => h.id === selected.id) ?? selected; setError(""); setMessage(""); try { await api(`/hotels/${selected.id}/plan`, { method: "PATCH", body: JSON.stringify({ plan_tier }) }); setMessage("Plan updated"); await load(); await loadKpis(); } catch (e) { setSelected(authoritative); setError((e as Error).message); } }
  const visible = hotels.filter(h => `${h.name} ${h.slug} ${h.id}`.toLowerCase().includes(search.toLowerCase())); const usedBindings = new Set(hotels.map(h => h.operational_binding));
  return <section className="admin-surface"><div className="workspace-heading"><div><p className="eyebrow">Network</p><h2>Hotel network</h2><p className="muted">Control-plane properties and authoritative multi-hotel analytics</p></div><span className="case-count">{hotels.length} properties</span></div>
    <form className="admin-create" onSubmit={register}><h3>Register property</h3><div className="form-field"><label htmlFor="hotel-id">Property id</label><input id="hotel-id" required placeholder="Property id" value={form.id} onChange={e => setForm({ ...form, id: e.target.value })} /></div><div className="form-field"><label htmlFor="hotel-slug">Slug</label><input id="hotel-slug" required placeholder="Slug" value={form.slug} onChange={e => setForm({ ...form, slug: e.target.value })} /></div><div className="form-field"><label htmlFor="hotel-name">Name</label><input id="hotel-name" required placeholder="Name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></div><div className="form-field"><label htmlFor="hotel-binding">Operational binding</label><select id="hotel-binding" value={form.operational_binding} onChange={e => setForm({ ...form, operational_binding: e.target.value })}><option disabled={usedBindings.has("HOTEL_DEMO_DB")}>HOTEL_DEMO_DB{usedBindings.has("HOTEL_DEMO_DB") ? " (assigned)" : ""}</option><option disabled={usedBindings.has("HOTEL_SECOND_DB")}>HOTEL_SECOND_DB{usedBindings.has("HOTEL_SECOND_DB") ? " (assigned)" : ""}</option></select></div><button type="submit" disabled={usedBindings.size >= 2}>Register property</button></form>
    <div className="report-controls"><div className="date-range"><label>Start <input aria-label="Network report start" type="date" value={range.start} onChange={e => setRange({ ...range, start: e.target.value })} /></label><label>End <input aria-label="Network report end" type="date" value={range.end} onChange={e => setRange({ ...range, end: e.target.value })} /></label></div><button type="button" onClick={() => void loadKpis()}>Refresh analytics</button></div>
    {message && <p className="success" role="status">{message}</p>}{error && <div className="error-row"><p className="error" role="alert">{error}</p><button type="button" onClick={() => { void load(); void loadKpis(); }}>Retry</button></div>}
    {loading ? <p className="muted loading-state" role="status">Loading hotel network…</p> : <><div className="kpi-grid">{kpis ? <><article><strong>Total hotels</strong><span>{kpis.total_hotels}</span></article><article><strong>Revenue</strong><span>${(kpis.total_revenue_cents / 100).toFixed(2)}</span></article><article><strong>Active bookings</strong><span>{kpis.total_active_bookings}</span></article><article><strong>Occupancy</strong><span>{kpis.average_occupancy_rate.toFixed(2)}%</span></article></> : <p className="muted">Analytics unavailable for this range.</p>}</div>
    <label className="admin-search">Filter properties <input aria-label="Filter properties" value={search} onChange={e => setSearch(e.target.value)} placeholder="Name, slug or id" /></label>{visible.length === 0 ? <div className="empty-state"><h3>{hotels.length ? "No properties match this filter" : "No properties registered"}</h3><p className="muted">Adjust the filter or register a property above.</p></div> : <div className="admin-network-layout"><div className="cards">{visible.map(h => <button type="button" className={selected?.id === h.id ? "network-row selected" : "network-row"} key={h.id} onClick={() => setSelected(h)}><strong>{h.name || h.slug}</strong><span>{h.slug} · {h.operational_binding}</span><small>{h.plan_tier} plan</small></button>)}</div>{selected && <article className="network-detail"><p className="eyebrow">Property detail</p><h3>{selected.name || selected.slug}</h3><p>{selected.address || "No address recorded"}</p><label>Plan <select aria-label="Property plan" value={selected.plan_tier} onChange={e => { setSelected({ ...selected, plan_tier: e.target.value }); void updatePlan(e.target.value); }}><option>BASIC</option><option>PRO</option><option>ENTERPRISE</option></select></label>{kpis?.hotels.find(row => row.hotel_id === selected.id) && <p>Revenue ${(kpis.hotels.find(row => row.hotel_id === selected.id)!.revenue_cents / 100).toFixed(2)} · ADR ${(kpis.hotels.find(row => row.hotel_id === selected.id)!.adr_cents / 100).toFixed(2)} · RevPAR ${(kpis.hotels.find(row => row.hotel_id === selected.id)!.rev_par_cents / 100).toFixed(2)}</p>}<button type="button" className="button-secondary" onClick={() => setSelected(null)}>Close property</button></article>}</div>}{kpis && <div className="cards revenue-ranking"><h3>Revenue ranking</h3>{kpis.hotels.map(row => <article key={row.hotel_id}><strong>{row.hotel_name}</strong><span>${(row.revenue_cents / 100).toFixed(2)} · {row.occupancy_rate.toFixed(2)}%</span></article>)}</div>}</>}</section>;
}
