#!/usr/bin/env bash
set -euo pipefail
repo_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd); cd "$repo_dir"; tmp_dir=$(mktemp -d); api_pid=""; web_pid=""; cleanup() { [[ -n "$web_pid" ]] && kill "$web_pid" 2>/dev/null || true; if [[ -n "$api_pid" ]]; then pkill -TERM -P "$api_pid" 2>/dev/null || true; kill "$api_pid" 2>/dev/null || true; fi; }; trap cleanup EXIT
wrangler="$repo_dir/node_modules/.bin/wrangler"; CI=1 "$wrangler" d1 migrations apply CONTROL_DB --local -c apps/api/wrangler.jsonc >/dev/null; CI=1 "$wrangler" d1 migrations apply HOTEL_DEMO_DB --local -c apps/api/wrangler.jsonc >/dev/null
CI=1 "$wrangler" d1 execute CONTROL_DB --local -c apps/api/wrangler.jsonc --command "INSERT OR REPLACE INTO control_hotels VALUES ('hotel-a','hotel-a','HOTEL_DEMO_DB',1); INSERT OR REPLACE INTO access_identity_mappings VALUES ('subject-a','a@test',1); INSERT OR REPLACE INTO hotel_memberships VALUES ('subject-a','hotel-a','admin',1);" >/dev/null
CI=1 "$wrangler" d1 execute HOTEL_DEMO_DB --local -c apps/api/wrangler.jsonc --command "DELETE FROM cash_closures; DELETE FROM financial_events; DELETE FROM payment_entries; DELETE FROM invoices; DELETE FROM extra_charges; DELETE FROM bookings WHERE id='cf-i06'; INSERT OR REPLACE INTO guests (id,full_name,email,created_at) VALUES ('cf-i06-guest','CF-I06 Guest','cf-i06@test','2026-01-01'); INSERT OR REPLACE INTO rooms (id,room_number,room_type,status,price_cents) VALUES ('cf-i06-room','I06','STANDARD','AVAILABLE',10000); INSERT INTO bookings (id,guest_id,room_id,check_in,check_out,status,total_cents,created_at,updated_at) VALUES ('cf-i06','cf-i06-guest','cf-i06-room','2026-09-01','2026-09-03','CONFIRMED',10000,'2026-01-01','2026-01-01');" >/dev/null
"$wrangler" dev --local --ip 127.0.0.1 --port 8787 --var LOCAL_DEV_AUTH:true -c apps/api/wrangler.jsonc >"$tmp_dir/api.log" 2>&1 & api_pid=$!; for _ in {1..30}; do curl -fsS http://127.0.0.1:8787/health >/dev/null 2>&1 && break; sleep 1; done
"$repo_dir/node_modules/.bin/vite" --host 127.0.0.1 --port 4174 --config apps/web/vite.config.ts >"$tmp_dir/web.log" 2>&1 & web_pid=$!; for _ in {1..30}; do curl -fsS http://127.0.0.1:4174/bookings >/dev/null 2>&1 && break; sleep 1; done
mkdir -p output/playwright; pwcli="${CODEX_HOME:-$HOME/.codex}/skills/playwright/scripts/playwright_cli.sh"; bash "$pwcli" -s cf-i06-billing-rework1 open about:blank >/dev/null; bash "$pwcli" -s cf-i06-billing-rework1 run-code --filename scripts/cf-i06-browser-regression.playwright.js; bash "$pwcli" -s cf-i06-billing-rework1 close >/dev/null
echo "CF-I06 browser responsive/error/close regression PASS"
