#!/usr/bin/env bash
set -euo pipefail
repo_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd); cd "$repo_dir"; wrangler="$repo_dir/node_modules/.bin/wrangler"; tmp_dir=$(mktemp -d); worker_pid=""; cleanup() { [[ -n "$worker_pid" ]] && kill "$worker_pid" 2>/dev/null || true; }; trap cleanup EXIT
CI=1 "$wrangler" d1 migrations apply CONTROL_DB --local -c apps/api/wrangler.jsonc >/dev/null
CI=1 "$wrangler" d1 migrations apply HOTEL_DEMO_DB --local -c apps/api/wrangler.jsonc >/dev/null
CI=1 "$wrangler" d1 execute CONTROL_DB --local -c apps/api/wrangler.jsonc --command "INSERT OR REPLACE INTO control_hotels VALUES ('hotel-a','hotel-a','HOTEL_DEMO_DB',1); INSERT OR REPLACE INTO access_identity_mappings VALUES ('subject-a','a@test',1); INSERT OR REPLACE INTO hotel_memberships VALUES ('subject-a','hotel-a','admin',1);" >/dev/null
CI=1 "$wrangler" d1 execute HOTEL_DEMO_DB --local -c apps/api/wrangler.jsonc --command "DELETE FROM financial_events; DELETE FROM payment_entries; DELETE FROM invoices; DELETE FROM extra_charges; DELETE FROM bookings WHERE id='cf-i06'; INSERT OR REPLACE INTO guests (id,full_name,email,created_at) VALUES ('cf-i06-guest','CF-I06 Guest','cf-i06@test','2026-01-01'); INSERT OR REPLACE INTO rooms (id,room_number,room_type,status,price_cents) VALUES ('cf-i06-room','I06','STANDARD','AVAILABLE',10000); INSERT INTO bookings (id,guest_id,room_id,check_in,check_out,status,total_cents,created_at,updated_at) VALUES ('cf-i06','cf-i06-guest','cf-i06-room','2026-09-01','2026-09-03','CONFIRMED',10000,'2026-01-01','2026-01-01');" >/dev/null
"$repo_dir/node_modules/.bin/wrangler" dev --local --ip 127.0.0.1 --port 8787 --var LOCAL_DEV_AUTH:true -c apps/api/wrangler.jsonc >"$tmp_dir/worker.log" 2>&1 & worker_pid=$!
for _ in {1..30}; do curl -fsS http://127.0.0.1:8787/health >/dev/null 2>&1 && break; sleep 1; done
base=http://127.0.0.1:8787/api/v1; common=(-H 'x-local-access-subject: subject-a' -H 'x-local-access-email: a@test' -H 'x-hotel-id: hotel-a' -H 'content-type: application/json'); request() { curl -sS -o "$tmp_dir/response.json" -w '%{http_code}' "${common[@]}" "$@"; }; assert_status() { [[ "$1" == "$2" ]] || { echo "expected $2 got $1: $(cat "$tmp_dir/response.json")" >&2; cat "$tmp_dir/worker.log" >&2; exit 1; }; }
status=$(request -X POST -d '{"description":"Late checkout","amount_cents":1500}' "$base/bookings/cf-i06/extra-charges"); assert_status "$status" 201
status=$(request "$base/bookings/cf-i06/invoice"); assert_status "$status" 200; node -e "const x=require('fs').readFileSync('$tmp_dir/response.json'); if(JSON.parse(x)!==null) process.exit(1)"
status=$(request -X POST -d '{"amount_cents":0,"payment_method":"CASH"}' "$base/bookings/cf-i06/payments"); assert_status "$status" 400
status=$(request -X POST -d '{"amount_cents":20000,"payment_method":"CASH"}' "$base/bookings/cf-i06/payments"); assert_status "$status" 409
status=$(request -X POST -d '{"amount_cents":5000,"payment_method":"CASH","payment_reference":"cash-1"}' "$base/bookings/cf-i06/payments"); assert_status "$status" 200
curl -sS -o "$tmp_dir/race-a.json" -w '%{http_code}' "${common[@]}" -X POST -d '{"amount_cents":6500,"payment_method":"CARD","payment_reference":"card-a"}' "$base/bookings/cf-i06/payments" >"$tmp_dir/race-a.status" & race_a=$!
curl -sS -o "$tmp_dir/race-b.json" -w '%{http_code}' "${common[@]}" -X POST -d '{"amount_cents":6500,"payment_method":"CARD","payment_reference":"card-b"}' "$base/bookings/cf-i06/payments" >"$tmp_dir/race-b.status" & race_b=$!
wait "$race_a" "$race_b"; node -e "const fs=require('fs'); const a=fs.readFileSync('$tmp_dir/race-a.status','utf8'), b=fs.readFileSync('$tmp_dir/race-b.status','utf8'); if([a,b].sort().join(',')!=='200,409') process.exit(1); const ok=JSON.parse(fs.readFileSync(a==='200'?'$tmp_dir/race-a.json':'$tmp_dir/race-b.json')); if(ok.invoice.paid_amount_cents!==11500||ok.invoice.status!=='PAID') process.exit(1)"
status=$(request -X POST -d '{"amount_cents":1,"payment_method":"CASH"}' "$base/bookings/cf-i06/payments"); assert_status "$status" 409
status=$(request "$base/bookings/cf-i06/payments"); assert_status "$status" 200; node -e "if(JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')).length!==2) process.exit(1)"
status=$(request "$base/billing/balance"); assert_status "$status" 200; node -e "const x=JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')); if(x.total_amount_cents!==11500||x.cash_amount_cents!==5000||x.card_amount_cents!==6500||x.payment_count!==2) process.exit(1)"
curl -sS -o "$tmp_dir/close-a.json" -w '%{http_code}' "${common[@]}" -X POST -d '{"expected_cash_amount_cents":5000,"counted_cash_amount_cents":4800,"handoff_to":"Night shift"}' "$base/billing/close-cash" >"$tmp_dir/close-a.status" & close_a=$!
curl -sS -o "$tmp_dir/close-b.json" -w '%{http_code}' "${common[@]}" -X POST -d '{"expected_cash_amount_cents":5000,"counted_cash_amount_cents":4900,"handoff_to":"Concurrent shift"}' "$base/billing/close-cash" >"$tmp_dir/close-b.status" & close_b=$!
wait "$close_a" "$close_b"; node -e "const fs=require('fs'); const a=fs.readFileSync('$tmp_dir/close-a.status','utf8'), b=fs.readFileSync('$tmp_dir/close-b.status','utf8'); if([a,b].sort().join(',')!=='200,409') process.exit(1); const ok=JSON.parse(fs.readFileSync(a==='200'?'$tmp_dir/close-a.json':'$tmp_dir/close-b.json')); if(ok.cash_difference_cents!==-200) process.exit(1)"
status=$(request -X POST -d '{"expected_cash_amount_cents":5000,"counted_cash_amount_cents":5000,"handoff_to":"Duplicate"}' "$base/billing/close-cash"); assert_status "$status" 409
CI=1 "$wrangler" d1 execute HOTEL_DEMO_DB --local -c apps/api/wrangler.jsonc --command "SELECT total_cents FROM bookings WHERE id='cf-i06'; SELECT COUNT(*) AS charges FROM extra_charges WHERE booking_id='cf-i06'; SELECT COUNT(*) AS events FROM financial_events WHERE booking_id='cf-i06';" --json >"$tmp_dir/db.json"
node -e "const r=JSON.parse(require('fs').readFileSync('$tmp_dir/db.json')).flatMap(x=>x.results); if(r[0].total_cents!==11500||r[1].charges!==1||r[2].events!==3) process.exit(1)"
echo "CF-I06 billing/atomic cents/closure regression PASS"
