#!/usr/bin/env bash
set -euo pipefail
repo_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd); cd "$repo_dir"; wrangler="$repo_dir/node_modules/.bin/wrangler"; tmp_dir=$(mktemp -d); worker_pid=""; cleanup() { [[ -n "$worker_pid" ]] && kill "$worker_pid" 2>/dev/null || true; }; trap cleanup EXIT
CI=1 "$wrangler" d1 migrations apply CONTROL_DB --local -c apps/api/wrangler.jsonc >/dev/null
CI=1 "$wrangler" d1 migrations apply HOTEL_DEMO_DB --local -c apps/api/wrangler.jsonc >/dev/null
CI=1 "$wrangler" d1 migrations apply HOTEL_SECOND_DB --local -c apps/api/wrangler.jsonc >/dev/null
CI=1 "$wrangler" d1 execute CONTROL_DB --local -c apps/api/wrangler.jsonc --command "INSERT OR REPLACE INTO control_hotels VALUES ('hotel-a','hotel-a','HOTEL_DEMO_DB',1),('hotel-b','hotel-b','HOTEL_SECOND_DB',1),('hotel-unknown','hotel-unknown','UNKNOWN_DB',1); INSERT OR REPLACE INTO access_identity_mappings VALUES ('subject-a','a@test',1),('subject-b','b@test',1),('subject-denied','denied@test',1),('subject-unknown','unknown@test',1); INSERT OR REPLACE INTO hotel_memberships VALUES ('subject-a','hotel-a','admin',1),('subject-b','hotel-b','admin',1),('subject-a','hotel-unknown','admin',1),('subject-denied','hotel-a','housekeeping',1),('subject-unknown','hotel-a','mystery',1);" >/dev/null
CI=1 "$wrangler" d1 execute HOTEL_DEMO_DB --local -c apps/api/wrangler.jsonc --command "DELETE FROM cash_closures; DELETE FROM financial_events; DELETE FROM payment_entries; DELETE FROM invoices; DELETE FROM extra_charges; DELETE FROM bookings WHERE id IN ('cf-i06','cf-i06-b'); INSERT OR REPLACE INTO guests (id,full_name,email,created_at) VALUES ('cf-i06-guest','CF-I06 Guest','cf-i06@test','2026-01-01'); INSERT OR REPLACE INTO rooms (id,room_number,room_type,status,price_cents) VALUES ('cf-i06-room','I06','STANDARD','AVAILABLE',10000),('cf-i06-room-b','I06B','STANDARD','AVAILABLE',2000); INSERT INTO bookings (id,guest_id,room_id,check_in,check_out,status,total_cents,created_at,updated_at) VALUES ('cf-i06','cf-i06-guest','cf-i06-room','2026-09-01','2026-09-03','CONFIRMED',10000,'2026-01-01','2026-01-01'),('cf-i06-b','cf-i06-guest','cf-i06-room-b','2026-10-01','2026-10-03','CONFIRMED',2000,'2026-01-01','2026-01-01');" >/dev/null
CI=1 "$wrangler" d1 execute HOTEL_SECOND_DB --local -c apps/api/wrangler.jsonc --command "DELETE FROM cash_closures; DELETE FROM financial_events; DELETE FROM payment_entries; DELETE FROM invoices; DELETE FROM extra_charges; DELETE FROM bookings WHERE id='tenant-b-booking'; INSERT OR REPLACE INTO guests (id,full_name,email,created_at) VALUES ('tenant-b-guest','Tenant B Guest','b@test','2026-01-01'); INSERT OR REPLACE INTO rooms (id,room_number,room_type,status,price_cents) VALUES ('tenant-b-room','B01','STANDARD','AVAILABLE',3000); INSERT INTO bookings (id,guest_id,room_id,check_in,check_out,status,total_cents,created_at,updated_at) VALUES ('tenant-b-booking','tenant-b-guest','tenant-b-room','2026-11-01','2026-11-03','CONFIRMED',3000,'2026-01-01','2026-01-01');" >/dev/null
"$repo_dir/node_modules/.bin/wrangler" dev --local --ip 127.0.0.1 --port 8787 --var LOCAL_DEV_AUTH:true -c apps/api/wrangler.jsonc >"$tmp_dir/worker.log" 2>&1 & worker_pid=$!
for _ in {1..30}; do curl -fsS http://127.0.0.1:8787/health >/dev/null 2>&1 && break; sleep 1; done
base=http://127.0.0.1:8787/api/v1; common=(-H 'x-local-access-subject: subject-a' -H 'x-local-access-email: a@test' -H 'x-hotel-id: hotel-a' -H 'content-type: application/json'); request() { curl -sS -o "$tmp_dir/response.json" -w '%{http_code}' "${common[@]}" "$@"; }; assert_status() { [[ "$1" == "$2" ]] || { echo "expected $2 got $1: $(cat "$tmp_dir/response.json")" >&2; cat "$tmp_dir/worker.log" >&2; exit 1; }; }
stop_worker() { if [[ -n "$worker_pid" ]]; then pkill -TERM -P "$worker_pid" 2>/dev/null || true; kill "$worker_pid" 2>/dev/null || true; worker_pid=""; fi; }
status=$(request -X POST -d '{"description":"Late checkout","amount_cents":1500}' "$base/bookings/cf-i06/extra-charges"); assert_status "$status" 201
status=$(curl -sS -o "$tmp_dir/failed-charge.json" -w '%{http_code}' "${common[@]}" -H 'x-test-fail-financial-write: extra-charge' -X POST -d '{"description":"Injected write failure","amount_cents":700}' "$base/bookings/cf-i06/extra-charges"); [[ "$status" == "409" ]] || { echo "authoritative extra-charge failure did not conflict" >&2; exit 1; }
status=$(request "$base/bookings/cf-i06/extra-charges"); assert_status "$status" 200; node -e "if(JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')).length!==1) process.exit(1)"
status=$(request -X POST -d '{"description":"Rejected charge","amount_cents":0}' "$base/bookings/cf-i06/extra-charges"); assert_status "$status" 400
status=$(request "$base/bookings/cf-i06/extra-charges"); assert_status "$status" 200; node -e "if(JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')).length!==1) process.exit(1)"
status=$(request "$base/bookings/cf-i06/invoice"); assert_status "$status" 200; node -e "const x=require('fs').readFileSync('$tmp_dir/response.json'); if(JSON.parse(x)!==null) process.exit(1)"
status=$(request "$base/bookings/cf-i06/payments"); assert_status "$status" 200; node -e "if(JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')).length!==0) process.exit(1)"
status=$(request -X POST -d '{"amount_cents":0,"payment_method":"CASH"}' "$base/bookings/cf-i06/payments"); assert_status "$status" 400
status=$(request -X POST -d '{"amount_cents":20000,"payment_method":"CASH"}' "$base/bookings/cf-i06/payments"); assert_status "$status" 409
status=$(request -X POST -d '{"amount_cents":5000,"payment_method":"CASH","payment_reference":"cash-1"}' "$base/bookings/cf-i06/payments"); assert_status "$status" 200
curl -sS -o "$tmp_dir/race-a.json" -w '%{http_code}' "${common[@]}" -X POST -d '{"amount_cents":6500,"payment_method":"TRANSFER","payment_reference":"transfer-a"}' "$base/bookings/cf-i06/payments" >"$tmp_dir/race-a.status" & race_a=$!
curl -sS -o "$tmp_dir/race-b.json" -w '%{http_code}' "${common[@]}" -X POST -d '{"amount_cents":6500,"payment_method":"TRANSFER","payment_reference":"transfer-b"}' "$base/bookings/cf-i06/payments" >"$tmp_dir/race-b.status" & race_b=$!
wait "$race_a" "$race_b"; node -e "const fs=require('fs'); const a=fs.readFileSync('$tmp_dir/race-a.status','utf8'), b=fs.readFileSync('$tmp_dir/race-b.status','utf8'); if([a,b].sort().join(',')!=='200,409') process.exit(1); const ok=JSON.parse(fs.readFileSync(a==='200'?'$tmp_dir/race-a.json':'$tmp_dir/race-b.json')); if(ok.invoice.paid_amount_cents!==11500||ok.invoice.status!=='PAID') process.exit(1)"
status=$(request -X POST -d '{"amount_cents":1,"payment_method":"CASH"}' "$base/bookings/cf-i06/payments"); assert_status "$status" 409
status=$(request "$base/bookings/cf-i06/payments"); assert_status "$status" 200; node -e "if(JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')).length!==2) process.exit(1)"
status=$(request -X POST -d '{"amount_cents":1000,"payment_method":"CASH","payment_reference":"b2-first"}' "$base/bookings/cf-i06-b/payments"); assert_status "$status" 200
status=$(request "$base/billing/balance"); assert_status "$status" 200; node -e "const x=JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')); if(x.total_amount_cents!==12500||x.cash_amount_cents!==6000||x.card_amount_cents!==6500||x.payment_count!==3) process.exit(1)"
status=$(request -X POST -d '{"payment_method":"CASH","payment_reference":"b2-settle"}' "$base/bookings/cf-i06-b/settle-payment"); assert_status "$status" 200; node -e "const x=JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')); if(x.amount_cents!==1000||x.invoice.status!=='PAID'||x.invoice.paid_amount_cents!==2000) process.exit(1)"
status=$(curl -sS -o "$tmp_dir/tenant-b-payment.json" -w '%{http_code}' -H 'x-local-access-subject: subject-b' -H 'x-local-access-email: b@test' -H 'x-hotel-id: hotel-b' -H 'content-type: application/json' -X POST -d '{"amount_cents":1000,"payment_method":"CASH","payment_reference":"tenant-b-payment"}' "$base/bookings/tenant-b-booking/payments"); [[ "$status" == "200" ]] || { echo "tenant-b financial fixture did not commit" >&2; exit 1; }
status=$(curl -sS -o "$tmp_dir/cross-a-read-b.json" -w '%{http_code}' "${common[@]}" "$base/bookings/tenant-b-booking/invoice"); [[ "$status" == "404" ]] || { echo "tenant-a read tenant-b object was not denied" >&2; exit 1; }
status=$(curl -sS -o "$tmp_dir/cross-a-write-b.json" -w '%{http_code}' "${common[@]}" -X POST -d '{"amount_cents":1,"payment_method":"CASH"}' "$base/bookings/tenant-b-booking/payments"); [[ "$status" == "404" ]] || { echo "tenant-a wrote tenant-b object" >&2; exit 1; }
status=$(curl -sS -o "$tmp_dir/cross-b-read-a.json" -w '%{http_code}' -H 'x-local-access-subject: subject-b' -H 'x-local-access-email: b@test' -H 'x-hotel-id: hotel-b' -H 'content-type: application/json' "$base/bookings/cf-i06/invoice"); [[ "$status" == "404" ]] || { echo "tenant-b read tenant-a object was not denied" >&2; exit 1; }
status=$(curl -sS -o "$tmp_dir/cross-b-write-a.json" -w '%{http_code}' -H 'x-local-access-subject: subject-b' -H 'x-local-access-email: b@test' -H 'x-hotel-id: hotel-b' -H 'content-type: application/json' -X POST -d '{"description":"cross tenant","amount_cents":1}' "$base/bookings/cf-i06/extra-charges"); [[ "$status" == "404" ]] || { echo "tenant-b wrote tenant-a object" >&2; exit 1; }
status=$(request -X POST -d '{"expected_cash_amount_cents":6000,"expected_total_amount_cents":12500,"expected_non_cash_amount_cents":6500,"expected_payment_count":3,"counted_cash_amount_cents":6000,"handoff_to":"Stale snapshot"}' "$base/billing/close-cash"); assert_status "$status" 409
status=$(request "$base/billing/balance"); assert_status "$status" 200; node -e "const x=JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')); if(x.total_amount_cents!==13500||x.cash_amount_cents!==7000||x.card_amount_cents!==6500||x.payment_count!==4) process.exit(1)"
curl -sS -o "$tmp_dir/close-a.json" -w '%{http_code}' "${common[@]}" -H 'x-request-id: same-close-request' -X POST -d '{"expected_cash_amount_cents":7000,"expected_total_amount_cents":13500,"expected_non_cash_amount_cents":6500,"expected_payment_count":4,"counted_cash_amount_cents":7200,"handoff_to":"Night shift"}' "$base/billing/close-cash" >"$tmp_dir/close-a.status" & close_a=$!
curl -sS -o "$tmp_dir/close-b.json" -w '%{http_code}' "${common[@]}" -H 'x-request-id: same-close-request' -X POST -d '{"expected_cash_amount_cents":7000,"expected_total_amount_cents":13500,"expected_non_cash_amount_cents":6500,"expected_payment_count":4,"counted_cash_amount_cents":6800,"handoff_to":"Concurrent shift"}' "$base/billing/close-cash" >"$tmp_dir/close-b.status" & close_b=$!
wait "$close_a" "$close_b"; node -e "const fs=require('fs'); const a=fs.readFileSync('$tmp_dir/close-a.status','utf8'), b=fs.readFileSync('$tmp_dir/close-b.status','utf8'); if([a,b].sort().join(',')!=='200,409') process.exit(1); const ok=JSON.parse(fs.readFileSync(a==='200'?'$tmp_dir/close-a.json':'$tmp_dir/close-b.json')); if(![200,-200].includes(ok.cash_difference_cents)) process.exit(1)"
status=$(request -X POST -d '{"expected_cash_amount_cents":7000,"expected_total_amount_cents":13500,"expected_non_cash_amount_cents":6500,"expected_payment_count":4,"counted_cash_amount_cents":7000,"handoff_to":"Duplicate"}' "$base/billing/close-cash"); assert_status "$status" 409
status=$(request -X POST -d '{"payment_method":"CASH"}' "$base/bookings/cf-i06/settle-payment"); assert_status "$status" 409
status=$(curl -sS -o "$tmp_dir/forbidden-write.json" -w '%{http_code}' -H 'x-local-access-subject: subject-denied' -H 'x-local-access-email: denied@test' -H 'x-hotel-id: hotel-a' -H 'content-type: application/json' -X POST -d '{"description":"forbidden","amount_cents":1}' "$base/bookings/cf-i06/extra-charges"); [[ "$status" == "403" ]] || { echo "forbidden financial write was not denied" >&2; exit 1; }
status=$(curl -sS -o "$tmp_dir/unknown-write.json" -w '%{http_code}' -H 'x-local-access-subject: subject-unknown' -H 'x-local-access-email: unknown@test' -H 'x-hotel-id: hotel-a' -H 'content-type: application/json' -X POST -d '{"amount_cents":1,"payment_method":"CASH"}' "$base/bookings/cf-i06/payments"); [[ "$status" == "403" ]] || { echo "unknown-role financial write was not denied" >&2; exit 1; }
status=$(curl -sS -o "$tmp_dir/forbidden.json" -w '%{http_code}' -H 'x-local-access-subject: subject-denied' -H 'x-local-access-email: denied@test' -H 'x-hotel-id: hotel-a' -H 'content-type: application/json' "$base/billing/balance"); [[ "$status" == "403" ]] || { echo "forbidden role was not denied" >&2; exit 1; }
status=$(curl -sS -o "$tmp_dir/unknown-role.json" -w '%{http_code}' -H 'x-local-access-subject: subject-unknown' -H 'x-local-access-email: unknown@test' -H 'x-hotel-id: hotel-a' -H 'content-type: application/json' "$base/billing/balance"); [[ "$status" == "403" ]] || { echo "unknown role was not denied" >&2; exit 1; }
status=$(curl -sS -o "$tmp_dir/unknown-binding.json" -w '%{http_code}' -H 'x-local-access-subject: subject-a' -H 'x-local-access-email: a@test' -H 'x-hotel-id: hotel-unknown' -H 'content-type: application/json' "$base/billing/balance"); [[ "$status" == "403" ]] || { echo "unknown binding was not denied" >&2; exit 1; }
status=$(curl -sS -o "$tmp_dir/unknown-hotel.json" -w '%{http_code}' -H 'x-local-access-subject: subject-a' -H 'x-local-access-email: a@test' -H 'x-hotel-id: unknown-hotel' -H 'content-type: application/json' "$base/billing/balance"); [[ "$status" == "403" ]] || { echo "unknown hotel was not denied" >&2; exit 1; }
status=$(request "$base/billing/closures"); assert_status "$status" 200; node -e "const x=JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')); if(x.length!==1||![200,-200].includes(x[0].cash_difference_cents)) process.exit(1)"
stop_worker
CI=1 "$wrangler" d1 execute HOTEL_DEMO_DB --local -c apps/api/wrangler.jsonc --command "SELECT COUNT(*) AS closures FROM cash_closures; SELECT COUNT(*) AS closure_events, COUNT(DISTINCT request_id) AS request_ids, COUNT(DISTINCT hotel_id) AS hotels FROM financial_events WHERE event_type='CASH_CLOSURE'; SELECT COUNT(*) AS b2_payments FROM payment_entries WHERE booking_id='cf-i06-b'; SELECT COUNT(*) AS settle_events FROM financial_events WHERE event_type='SETTLE_PAYMENT' AND booking_id='cf-i06-b'; SELECT actor_subject,request_id,hotel_id FROM financial_events WHERE event_type='SETTLE_PAYMENT' AND booking_id='cf-i06-b'; SELECT COUNT(*) AS a_charges FROM extra_charges WHERE booking_id='cf-i06';" --json >"$tmp_dir/closure-events.json"
CI=1 "$wrangler" d1 execute HOTEL_SECOND_DB --local -c apps/api/wrangler.jsonc --command "SELECT COUNT(*) AS b_payments FROM payment_entries WHERE booking_id='tenant-b-booking'; SELECT COUNT(*) AS b_charges FROM extra_charges WHERE booking_id='tenant-b-booking';" --json >"$tmp_dir/tenant-b-state.json"
node -e "const x=require('fs').readFileSync('$tmp_dir/closure-events.json','utf8'); const rows=JSON.parse(x).flatMap(x=>x.results||[]); if(rows[0].closures!==1||rows[1].closure_events!==1||rows[1].request_ids!==1||rows[1].hotels!==1||rows[2].b2_payments!==2||rows[3].settle_events!==1||rows[4].actor_subject!=='subject-a'||!rows[4].request_id||rows[4].hotel_id!=='hotel-a'||rows[5].a_charges!==1) process.exit(1)"
node -e "const x=require('fs').readFileSync('$tmp_dir/tenant-b-state.json','utf8'); const rows=JSON.parse(x).flatMap(x=>x.results||[]); if(rows[0].b_payments!==1||rows[1].b_charges!==0) process.exit(1)"
echo "CF-I06 billing/atomic cents/closure regression PASS"
