#!/usr/bin/env bash
set -euo pipefail
repo_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd); cd "$repo_dir"; wrangler="$repo_dir/node_modules/.bin/wrangler"; tmp_dir=$(mktemp -d); worker_pid=""; cleanup() { [[ -n "$worker_pid" ]] && kill "$worker_pid" 2>/dev/null || true; }; trap cleanup EXIT
CI=1 "$wrangler" d1 migrations apply CONTROL_DB --local -c apps/api/wrangler.jsonc >/dev/null
CI=1 "$wrangler" d1 migrations apply HOTEL_DEMO_DB --local -c apps/api/wrangler.jsonc >/dev/null
CI=1 "$wrangler" d1 execute CONTROL_DB --local -c apps/api/wrangler.jsonc --command "INSERT OR REPLACE INTO control_hotels VALUES ('hotel-a','hotel-a','HOTEL_DEMO_DB',1); INSERT OR REPLACE INTO access_identity_mappings VALUES ('subject-a','a@test',1); INSERT OR REPLACE INTO hotel_memberships VALUES ('subject-a','hotel-a','admin',1);" >/dev/null
CI=1 "$wrangler" d1 execute HOTEL_DEMO_DB --local -c apps/api/wrangler.jsonc --command "DELETE FROM cash_closures; DELETE FROM financial_events; DELETE FROM payment_entries; DELETE FROM invoices; DELETE FROM extra_charges; DELETE FROM bookings WHERE id IN ('cf-i06','cf-i06-b'); INSERT OR REPLACE INTO guests (id,full_name,email,created_at) VALUES ('cf-i06-guest','CF-I06 Guest','cf-i06@test','2026-01-01'); INSERT OR REPLACE INTO rooms (id,room_number,room_type,status,price_cents) VALUES ('cf-i06-room','I06','STANDARD','AVAILABLE',10000),('cf-i06-room-b','I06B','STANDARD','AVAILABLE',2000); INSERT INTO bookings (id,guest_id,room_id,check_in,check_out,status,total_cents,created_at,updated_at) VALUES ('cf-i06','cf-i06-guest','cf-i06-room','2026-09-01','2026-09-03','CONFIRMED',10000,'2026-01-01','2026-01-01'),('cf-i06-b','cf-i06-guest','cf-i06-room-b','2026-10-01','2026-10-03','CONFIRMED',2000,'2026-01-01','2026-01-01');" >/dev/null
"$repo_dir/node_modules/.bin/wrangler" dev --local --ip 127.0.0.1 --port 8787 --var LOCAL_DEV_AUTH:true -c apps/api/wrangler.jsonc >"$tmp_dir/worker.log" 2>&1 & worker_pid=$!
for _ in {1..30}; do curl -fsS http://127.0.0.1:8787/health >/dev/null 2>&1 && break; sleep 1; done
base=http://127.0.0.1:8787/api/v1; common=(-H 'x-local-access-subject: subject-a' -H 'x-local-access-email: a@test' -H 'x-hotel-id: hotel-a' -H 'content-type: application/json'); request() { curl -sS -o "$tmp_dir/response.json" -w '%{http_code}' "${common[@]}" "$@"; }; assert_status() { [[ "$1" == "$2" ]] || { echo "expected $2 got $1: $(cat "$tmp_dir/response.json")" >&2; cat "$tmp_dir/worker.log" >&2; exit 1; }; }
stop_worker() { if [[ -n "$worker_pid" ]]; then pkill -TERM -P "$worker_pid" 2>/dev/null || true; kill "$worker_pid" 2>/dev/null || true; worker_pid=""; fi; }
status=$(request -X POST -d '{"description":"Late checkout","amount_cents":1500}' "$base/bookings/cf-i06/extra-charges"); assert_status "$status" 201
status=$(request "$base/bookings/cf-i06/invoice"); assert_status "$status" 200; node -e "const x=require('fs').readFileSync('$tmp_dir/response.json'); if(JSON.parse(x)!==null) process.exit(1)"
status=$(request "$base/bookings/cf-i06/payments"); assert_status "$status" 200; node -e "if(JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')).length!==0) process.exit(1)"
status=$(request -X POST -d '{"amount_cents":0,"payment_method":"CASH"}' "$base/bookings/cf-i06/payments"); assert_status "$status" 400
status=$(request -X POST -d '{"amount_cents":20000,"payment_method":"CASH"}' "$base/bookings/cf-i06/payments"); assert_status "$status" 409
status=$(request -X POST -d '{"amount_cents":5000,"payment_method":"CASH","payment_reference":"cash-1"}' "$base/bookings/cf-i06/payments"); assert_status "$status" 200
curl -sS -o "$tmp_dir/race-a.json" -w '%{http_code}' "${common[@]}" -X POST -d '{"amount_cents":6500,"payment_method":"TRANSFER","payment_reference":"transfer-a"}' "$base/bookings/cf-i06/payments" >"$tmp_dir/race-a.status" & race_a=$!
curl -sS -o "$tmp_dir/race-b.json" -w '%{http_code}' "${common[@]}" -X POST -d '{"amount_cents":6500,"payment_method":"TRANSFER","payment_reference":"transfer-b"}' "$base/bookings/cf-i06/payments" >"$tmp_dir/race-b.status" & race_b=$!
wait "$race_a" "$race_b"; node -e "const fs=require('fs'); const a=fs.readFileSync('$tmp_dir/race-a.status','utf8'), b=fs.readFileSync('$tmp_dir/race-b.status','utf8'); if([a,b].sort().join(',')!=='200,409') process.exit(1); const ok=JSON.parse(fs.readFileSync(a==='200'?'$tmp_dir/race-a.json':'$tmp_dir/race-b.json')); if(ok.invoice.paid_amount_cents!==11500||ok.invoice.status!=='PAID') process.exit(1)"
status=$(request -X POST -d '{"amount_cents":1,"payment_method":"CASH"}' "$base/bookings/cf-i06/payments"); assert_status "$status" 409
status=$(request "$base/bookings/cf-i06/payments"); assert_status "$status" 200; node -e "if(JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')).length!==2) process.exit(1)"
status=$(request -X POST -d '{"amount_cents":1000,"payment_method":"CASH","payment_reference":"b2-first"}' "$base/bookings/cf-i06-b/payments"); assert_status "$status" 200
status=$(request "$base/billing/balance"); assert_status "$status" 200; node -e "const x=JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')); if(x.total_amount_cents!==12500||x.cash_amount_cents!==6000||x.card_amount_cents!==6500||x.payment_count!==3) process.exit(1)"
status=$(request -X POST -d '{"amount_cents":1000,"payment_method":"CASH","payment_reference":"b2-second"}' "$base/bookings/cf-i06-b/payments"); assert_status "$status" 200
status=$(request -X POST -d '{"expected_cash_amount_cents":6000,"expected_total_amount_cents":12500,"expected_non_cash_amount_cents":6500,"expected_payment_count":3,"counted_cash_amount_cents":6000,"handoff_to":"Stale snapshot"}' "$base/billing/close-cash"); assert_status "$status" 409
status=$(request "$base/billing/balance"); assert_status "$status" 200; node -e "const x=JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')); if(x.total_amount_cents!==13500||x.cash_amount_cents!==7000||x.card_amount_cents!==6500||x.payment_count!==4) process.exit(1)"
curl -sS -o "$tmp_dir/close-a.json" -w '%{http_code}' "${common[@]}" -X POST -d '{"expected_cash_amount_cents":7000,"expected_total_amount_cents":13500,"expected_non_cash_amount_cents":6500,"expected_payment_count":4,"counted_cash_amount_cents":7200,"handoff_to":"Night shift"}' "$base/billing/close-cash" >"$tmp_dir/close-a.status" & close_a=$!
curl -sS -o "$tmp_dir/close-b.json" -w '%{http_code}' "${common[@]}" -X POST -d '{"expected_cash_amount_cents":7000,"expected_total_amount_cents":13500,"expected_non_cash_amount_cents":6500,"expected_payment_count":4,"counted_cash_amount_cents":6800,"handoff_to":"Concurrent shift"}' "$base/billing/close-cash" >"$tmp_dir/close-b.status" & close_b=$!
wait "$close_a" "$close_b"; node -e "const fs=require('fs'); const a=fs.readFileSync('$tmp_dir/close-a.status','utf8'), b=fs.readFileSync('$tmp_dir/close-b.status','utf8'); if([a,b].sort().join(',')!=='200,409') process.exit(1); const ok=JSON.parse(fs.readFileSync(a==='200'?'$tmp_dir/close-a.json':'$tmp_dir/close-b.json')); if(![200,-200].includes(ok.cash_difference_cents)) process.exit(1)"
status=$(request -X POST -d '{"expected_cash_amount_cents":7000,"expected_total_amount_cents":13500,"expected_non_cash_amount_cents":6500,"expected_payment_count":4,"counted_cash_amount_cents":7000,"handoff_to":"Duplicate"}' "$base/billing/close-cash"); assert_status "$status" 409
status=$(request -X POST -d '{"payment_method":"CASH"}' "$base/bookings/cf-i06/settle-payment"); assert_status "$status" 409
status=$(curl -sS -o "$tmp_dir/unknown-hotel.json" -w '%{http_code}' -H 'x-local-access-subject: subject-a' -H 'x-local-access-email: a@test' -H 'x-hotel-id: unknown-hotel' -H 'content-type: application/json' "$base/billing/balance"); [[ "$status" == "403" ]] || { echo "unknown hotel was not denied" >&2; exit 1; }
status=$(request "$base/billing/closures"); assert_status "$status" 200; node -e "const x=JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')); if(x.length!==1||![200,-200].includes(x[0].cash_difference_cents)) process.exit(1)"
stop_worker
echo "CF-I06 billing/atomic cents/closure regression PASS"
