#!/usr/bin/env bash
set -euo pipefail
repo_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd); cd "$repo_dir"; tmp_dir=$(mktemp -d); api_pid=""; web_pid=""
collect_tree(){ local parent="$1" child; printf '%s\n' "$parent"; while read -r child; do [[ -n "$child" ]] && collect_tree "$child"; done < <(pgrep -P "$parent" || true); }
cleanup(){ local root pid; local -a owned=(); for root in "$api_pid" "$web_pid"; do [[ -n "$root" ]] || continue; while read -r pid; do owned+=("$pid"); done < <(collect_tree "$root"); done; for pid in "${owned[@]}"; do kill -TERM "$pid" 2>/dev/null || true; done; for _ in {1..50}; do local live=0; for pid in "${owned[@]}"; do kill -0 "$pid" 2>/dev/null && live=1; done; (( live == 0 )) && { wait "$api_pid" "$web_pid" 2>/dev/null || true; api_pid=""; web_pid=""; return 0; }; sleep 0.1; done; for pid in "${owned[@]}"; do kill -KILL "$pid" 2>/dev/null || true; done; }
trap 'status=$?; cleanup || status=1; exit "$status"' EXIT
wrangler="$repo_dir/node_modules/.bin/wrangler"; for db in CONTROL_DB HOTEL_DEMO_DB HOTEL_SECOND_DB; do CI=1 "$wrangler" d1 migrations apply "$db" --local -c apps/api/wrangler.jsonc >/dev/null; done
CI=1 "$wrangler" d1 execute CONTROL_DB --local -c apps/api/wrangler.jsonc --command "DELETE FROM network_memberships; DELETE FROM hotel_memberships; DELETE FROM hotel_admin_metadata; DELETE FROM access_identity_mappings; DELETE FROM control_hotels; INSERT INTO control_hotels VALUES ('hotel-a','hotel-a','HOTEL_DEMO_DB',1),('hotel-b','hotel-b','HOTEL_SECOND_DB',1); INSERT INTO hotel_admin_metadata(hotel_id,name,address,plan_tier) VALUES ('hotel-a','Hotel A','A Street','BASIC'),('hotel-b','Hotel B','B Street','PRO'); INSERT INTO access_identity_mappings VALUES ('subject-a','a@test',1),('subject-network','network@test',1),('subject-hk','hk@test',1); INSERT INTO hotel_memberships VALUES ('subject-a','hotel-a','admin',1),('subject-hk','hotel-a','housekeeping',1); INSERT INTO network_memberships VALUES ('subject-network','saas_admin',1);" >/dev/null
for db in HOTEL_DEMO_DB HOTEL_SECOND_DB; do CI=1 "$wrangler" d1 execute "$db" --local -c apps/api/wrangler.jsonc --command "DELETE FROM housekeeping_events; DELETE FROM maintenance_cases; DELETE FROM payment_entries; DELETE FROM invoices; DELETE FROM financial_events; DELETE FROM room_inventory_nights; DELETE FROM room_holds; DELETE FROM bookings; DELETE FROM rooms; DELETE FROM guests;" >/dev/null; done
CI=1 "$wrangler" d1 execute HOTEL_DEMO_DB --local -c apps/api/wrangler.jsonc --command "INSERT INTO rooms VALUES ('room-a1','101','STANDARD','AVAILABLE',10000),('room-a2','102','STANDARD','AVAILABLE',12000); INSERT INTO guests VALUES ('guest-a','Hotel A Guest','a@guest.test',NULL,'2026-01-01'); INSERT INTO bookings(id,guest_id,room_id,check_in,check_out,status,total_cents,created_at,updated_at) VALUES ('booking-a1','guest-a','room-a1','2026-09-02','2026-09-04','CONFIRMED',12345,'2026-01-01','2026-01-01'); INSERT INTO room_inventory_nights VALUES ('room-a1','2026-09-02','booking-a1'),('room-a1','2026-09-03','booking-a1');" >/dev/null
CI=1 "$wrangler" d1 execute HOTEL_SECOND_DB --local -c apps/api/wrangler.jsonc --command "INSERT INTO rooms VALUES ('room-b1','201','STANDARD','AVAILABLE',20000); INSERT INTO guests VALUES ('guest-b','Hotel B Guest','b@guest.test',NULL,'2026-01-01'); INSERT INTO bookings(id,guest_id,room_id,check_in,check_out,status,total_cents,created_at,updated_at) VALUES ('booking-b1','guest-b','room-b1','2026-09-03','2026-09-04','CONFIRMED',20000,'2026-01-01','2026-01-01'); INSERT INTO room_inventory_nights VALUES ('room-b1','2026-09-03','booking-b1');" >/dev/null
if curl -fsS http://127.0.0.1:8787/health >/dev/null 2>&1 || curl -fsS http://127.0.0.1:4174/reports >/dev/null 2>&1; then echo "CF-I08 browser ports already occupied" >&2; exit 1; fi
"$wrangler" dev --local --ip 127.0.0.1 --port 8787 --var LOCAL_DEV_AUTH:true -c apps/api/wrangler.jsonc >"$tmp_dir/api.log" 2>&1 & api_pid=$!; for _ in {1..30}; do curl -fsS http://127.0.0.1:8787/health >/dev/null 2>&1 && break; sleep 1; done
"$repo_dir/node_modules/.bin/vite" --host 127.0.0.1 --port 4174 --config apps/web/vite.config.ts >"$tmp_dir/web.log" 2>&1 & web_pid=$!; for _ in {1..30}; do curl -fsS http://127.0.0.1:4174/reports >/dev/null 2>&1 && break; sleep 1; done
pwcli="${CODEX_HOME:-$HOME/.codex}/skills/playwright/scripts/playwright_cli.sh"; bash "$pwcli" -s cf-i08-admin open about:blank >/dev/null; bash "$pwcli" -s cf-i08-admin run-code --filename scripts/cf-i08-browser-regression.playwright.js; bash "$pwcli" -s cf-i08-admin close >/dev/null; cleanup; trap - EXIT; echo "CF-I08 responsive/integrated browser regression PASS"
