#!/usr/bin/env bash
set -euo pipefail
export WRANGLER_SEND_METRICS=false
repo_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd); cd "$repo_dir"; wrangler="$repo_dir/node_modules/.bin/wrangler"; tmp_dir=$(mktemp -d); worker_pid=""
run_d1(){ CI=1 timeout 6s "$wrangler" "$@" >/dev/null || { local rc=$?; [[ "$rc" == 124 ]]; }; }
collect_tree(){ local parent="$1" child; printf '%s\n' "$parent"; while read -r child; do [[ -n "$child" ]] && collect_tree "$child"; done < <(pgrep -P "$parent" || true); }
cleanup(){ local pid; local -a owned=(); [[ -n "$worker_pid" ]] || return 0; while read -r pid; do owned+=("$pid"); done < <(collect_tree "$worker_pid"); for pid in "${owned[@]}"; do kill -TERM "$pid" 2>/dev/null || true; done; for _ in {1..50}; do local live=0; for pid in "${owned[@]}"; do kill -0 "$pid" 2>/dev/null && live=1; done; (( live == 0 )) && { wait "$worker_pid" 2>/dev/null || true; worker_pid=""; return 0; }; sleep 0.1; done; for pid in "${owned[@]}"; do kill -KILL "$pid" 2>/dev/null || true; done; }
trap cleanup EXIT
for db in CONTROL_DB HOTEL_DEMO_DB HOTEL_SECOND_DB; do run_d1 d1 migrations apply "$db" --local -c apps/api/wrangler.jsonc; done
run_d1 d1 execute CONTROL_DB --local -c apps/api/wrangler.jsonc --command "DELETE FROM network_memberships; DELETE FROM hotel_memberships; DELETE FROM hotel_admin_metadata; DELETE FROM access_identity_mappings; DELETE FROM control_hotels; INSERT INTO control_hotels VALUES ('hotel-a','hotel-a','HOTEL_DEMO_DB',1),('hotel-b','hotel-b','HOTEL_SECOND_DB',1); INSERT INTO hotel_admin_metadata(hotel_id,name,address,plan_tier) VALUES ('hotel-a','Hotel A','A Street','BASIC'),('hotel-b','Hotel B','B Street','PRO'); INSERT INTO access_identity_mappings VALUES ('subject-a','a@test',1),('subject-b','b@test',1),('subject-ops','ops@test',1),('subject-network','network@test',1),('subject-hk','hk@test',1); INSERT INTO hotel_memberships VALUES ('subject-a','hotel-a','admin',1),('subject-ops','hotel-a','ops',1),('subject-b','hotel-b','admin',1),('subject-hk','hotel-a','housekeeping',1); INSERT INTO network_memberships VALUES ('subject-network','saas_admin',1);"
for db in HOTEL_DEMO_DB HOTEL_SECOND_DB; do run_d1 d1 execute "$db" --local -c apps/api/wrangler.jsonc --command "DELETE FROM housekeeping_events; DELETE FROM maintenance_cases; DELETE FROM payment_entries; DELETE FROM invoices; DELETE FROM financial_events; DELETE FROM room_inventory_nights; DELETE FROM room_holds; DELETE FROM bookings; DELETE FROM rooms; DELETE FROM guests;"; done
run_d1 d1 execute HOTEL_DEMO_DB --local -c apps/api/wrangler.jsonc --command "INSERT INTO rooms VALUES ('room-a1','101','STANDARD','AVAILABLE',10000),('room-a2','102','STANDARD','AVAILABLE',12000); INSERT INTO guests VALUES ('guest-a','Hotel A Guest','a@guest.test',NULL,'2026-01-01'); INSERT INTO bookings(id,guest_id,room_id,check_in,check_out,status,total_cents,created_at,updated_at) VALUES ('booking-a1','guest-a','room-a1','2026-09-02','2026-09-04','CONFIRMED',12345,'2026-01-01','2026-01-01'),('booking-a-cancel','guest-a','room-a2','2026-09-05','2026-09-06','CANCELLED',99999,'2026-01-01','2026-01-01'),('booking-a-noshow','guest-a','room-a2','2026-09-07','2026-09-08','NO_SHOW',77777,'2026-01-01','2026-01-01'); INSERT INTO room_inventory_nights VALUES ('room-a1','2026-09-02','booking-a1'),('room-a1','2026-09-03','booking-a1');"
run_d1 d1 execute HOTEL_SECOND_DB --local -c apps/api/wrangler.jsonc --command "INSERT INTO rooms VALUES ('room-b1','201','STANDARD','AVAILABLE',20000); INSERT INTO guests VALUES ('guest-b','Hotel B Guest','b@guest.test',NULL,'2026-01-01'); INSERT INTO bookings(id,guest_id,room_id,check_in,check_out,status,total_cents,created_at,updated_at) VALUES ('booking-b1','guest-b','room-b1','2026-09-03','2026-09-04','CONFIRMED',20000,'2026-01-01','2026-01-01'); INSERT INTO room_inventory_nights VALUES ('room-b1','2026-09-03','booking-b1');"
run_d1 d1 execute HOTEL_DEMO_DB --local -c apps/api/wrangler.jsonc --command "UPDATE rooms SET room_type='STANDARD', status='AVAILABLE', price_cents=10000 WHERE id='room-a1'; UPDATE rooms SET room_type='STANDARD', status='AVAILABLE', price_cents=12000 WHERE id='room-a2';"
npx --yes wrangler dev --local --ip 127.0.0.1 --port 8787 --var LOCAL_DEV_AUTH:true -c apps/api/wrangler.jsonc >"$tmp_dir/worker.log" 2>&1 & worker_pid=$!; for _ in {1..30}; do curl -fsS http://127.0.0.1:8787/health >/dev/null 2>&1 && break; sleep 1; done
base=http://127.0.0.1:8787/api/v1
today=$(date -u +%F)
request(){ curl -sS -o "$tmp_dir/response.json" -w '%{http_code}' -H "x-local-access-subject: $1" -H "x-local-access-email: $2" -H 'x-hotel-id: hotel-a' -H 'content-type: application/json' "$base$3"; }
expect(){ [[ "$1" == "$2" ]] || { echo "expected $2 got $1: $(cat "$tmp_dir/response.json")" >&2; cat "$tmp_dir/worker.log" >&2; exit 1; }; }
status=$(request subject-a a@test '/reports/revenue?start=2026-09-01&end=2026-10-01'); expect "$status" 200
node -e "const x=JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')); if(x.length!==1||x[0].date!=='2026-09-02'||x[0].revenue_cents!==12345) process.exit(1)"
status=$(request subject-a a@test '/reports/occupancy?start=2026-09-01&end=2026-10-01'); expect "$status" 200
node -e "const x=JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')); if(x.length!==31||x.find(r=>r.date==='2026-09-02').occupied_rooms!==1||x.find(r=>r.date==='2026-09-05').occupied_rooms!==0||x.find(r=>r.date==='2026-09-02').total_rooms!==2) process.exit(1)"
status=$(request subject-a a@test '/reports/revenue?start=2026-10-01&end=2026-09-01'); expect "$status" 400
status=$(request subject-a a@test '/reports/revenue?start=2026-09-02&end=2026-09-02'); expect "$status" 200
status=$(request subject-a a@test '/reports/revenue'); expect "$status" 200
status=$(request subject-a a@test "/reports/revenue?start=$today"); expect "$status" 200
status=$(request subject-a a@test "/reports/revenue?end=$today"); expect "$status" 200
default_old=$(date -u -d "$today -33 days" +%F); default_old_end=$(date -u -d "$default_old +1 day" +%F); default_inside=$(date -u -d "$today -25 days" +%F); default_inside_end=$(date -u -d "$default_inside +1 day" +%F); start_inside=$(date -u -d "$today -10 days" +%F); start_inside_end=$(date -u -d "$start_inside +1 day" +%F); default_end=$(date -u -d "$today -5 days" +%F); start_only=$(date -u -d "$today -20 days" +%F)
run_d1 d1 execute HOTEL_DEMO_DB --local -c apps/api/wrangler.jsonc --command "DELETE FROM room_inventory_nights; DELETE FROM bookings; INSERT INTO bookings(id,guest_id,room_id,check_in,check_out,status,total_cents,created_at,updated_at) VALUES ('default-old','guest-a','room-a1','$default_old','$default_old_end','CONFIRMED',1111,'2026-01-01','2026-01-01'),('default-inside','guest-a','room-a2','$default_inside','$default_inside_end','CONFIRMED',2222,'2026-01-01','2026-01-01'),('start-inside','guest-a','room-a1','$start_inside','$start_inside_end','CONFIRMED',3333,'2026-01-01','2026-01-01');"
status=$(request subject-a a@test '/reports/revenue'); expect "$status" 200
node -e "const x=JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')); if(x.length!==2||!x.some(r=>r.date==='$default_inside')||!x.some(r=>r.date==='$start_inside')||x.some(r=>r.date==='$default_old')) process.exit(1)"
status=$(request subject-a a@test "/reports/revenue?start=$start_only"); expect "$status" 200
node -e "const x=JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')); if(x.length!==1||x[0].date!=='$start_inside'||x[0].revenue_cents!==3333) process.exit(1)"
status=$(request subject-a a@test "/reports/revenue?end=$default_end"); expect "$status" 200
node -e "const x=JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')); if(x.length!==2||!x.some(r=>r.date==='$default_inside'&&r.revenue_cents===2222)||!x.some(r=>r.date==='$start_inside'&&r.revenue_cents===3333)||x.some(r=>r.date==='$default_old')) process.exit(1)"
run_d1 d1 execute HOTEL_DEMO_DB --local -c apps/api/wrangler.jsonc --command "DELETE FROM room_inventory_nights; DELETE FROM bookings; INSERT INTO bookings(id,guest_id,room_id,check_in,check_out,status,total_cents,created_at,updated_at) VALUES ('booking-a1','guest-a','room-a1','2026-09-02','2026-09-04','CONFIRMED',12345,'2026-01-01','2026-01-01'),('booking-a-cancel','guest-a','room-a2','2026-09-05','2026-09-06','CANCELLED',99999,'2026-01-01','2026-01-01'),('booking-a-noshow','guest-a','room-a2','2026-09-07','2026-09-08','NO_SHOW',77777,'2026-01-01','2026-01-01'); INSERT INTO room_inventory_nights VALUES ('room-a1','2026-09-02','booking-a1'),('room-a1','2026-09-03','booking-a1');"
status=$(request subject-ops ops@test '/reports/revenue?start=2026-09-01&end=2026-10-01'); expect "$status" 200
status=$(request subject-ops ops@test '/reports/occupancy?start=2026-09-01&end=2026-10-01'); expect "$status" 200
status=$(curl -sS -o "$tmp_dir/response.json" -w '%{http_code}' -H 'x-local-access-subject: subject-network' -H 'x-local-access-email: network@test' "$base/hotels/network-kpis?start=2026-09-01&end=2026-10-01"); expect "$status" 200
node -e "const x=JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')); if(x.total_hotels!==2||x.total_revenue_cents!==32345||x.total_active_bookings!==2||x.hotels[0].hotel_id!=='hotel-b'||x.hotels[1].hotel_id!=='hotel-a'||x.hotels[0].revenue_cents!==20000||x.hotels[0].occupancy_rate!==0) process.exit(1)"
status=$(curl -sS -o "$tmp_dir/response.json" -w '%{http_code}' -H 'x-local-access-subject: subject-a' -H 'x-local-access-email: a@test' -H 'x-hotel-id: hotel-a' "$base/hotels/network-kpis?start=2026-09-01&end=2026-10-01"); expect "$status" 403
status=$(curl -sS -o "$tmp_dir/response.json" -w '%{http_code}' -H 'x-local-access-subject: subject-a' -H 'x-local-access-email: a@test' -H 'x-hotel-id: hotel-b' "$base/reports/revenue?start=2026-09-01&end=2026-10-01"); expect "$status" 403
status=$(curl -sS -o "$tmp_dir/response.json" -w '%{http_code}' -H 'x-local-access-subject: subject-hk' -H 'x-local-access-email: hk@test' -H 'x-hotel-id: hotel-a' "$base/housekeeping/board?date=2026-09-08"); expect "$status" 200
node -e "const x=JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')); if(x.departures_today.length!==0||x.rooms.some(r=>r.room_id==='room-a2'&&r.turnover_today)) process.exit(1)"
run_d1 d1 execute CONTROL_DB --local -c apps/api/wrangler.jsonc --command "INSERT INTO control_hotels VALUES ('hotel-bad','hotel-bad','UNKNOWN_DB',1);"
status=$(curl -sS -o "$tmp_dir/response.json" -w '%{http_code}' -H 'x-local-access-subject: subject-network' -H 'x-local-access-email: network@test' "$base/hotels/network-kpis?start=2026-09-01&end=2026-10-01"); expect "$status" 503
today=$(date -u +%F); tomorrow=$(date -u -d "$today +1 day" +%F); yesterday=$(date -u -d "$today -1 day" +%F); month_start=$(date -u -d "$today" +%Y-%m-01)
run_d1 d1 execute HOTEL_DEMO_DB --local -c apps/api/wrangler.jsonc --command "DELETE FROM room_inventory_nights; DELETE FROM bookings; INSERT INTO bookings(id,guest_id,room_id,check_in,check_out,status,total_cents,created_at,updated_at) VALUES ('dash-arrival','guest-a','room-a1','$today','$tomorrow','CONFIRMED',5000,'2026-01-01','2026-01-01'),('dash-departure','guest-a','room-a2','$yesterday','$today','CHECKED_IN',7000,'2026-01-01','2026-01-01');"
status=$(request subject-a a@test '/analytics/kpis'); expect "$status" 200
node -e "const x=JSON.parse(require('fs').readFileSync('$tmp_dir/response.json')); const revenue=5000+('$yesterday'>='$month_start'?7000:0); const adr=Math.trunc(revenue/2); if(x.revenue_month_cents!==revenue||x.active_bookings_count!==2||x.occupancy_rate!==50||x.today_check_ins!==1||x.adr_cents!==adr||x.rev_par_cents!==Math.trunc(adr/2)||x.arrivals_today.length!==1||x.arrivals_today[0].booking_id!=='dash-arrival'||x.arrivals_today[0].guest_name!=='Hotel A Guest'||x.arrivals_today[0].room_number!=='101'||x.arrivals_today[0].status!=='Confirmed'||x.departures_today.length!==1||x.departures_today[0].booking_id!=='dash-departure'||x.departures_today[0].status!=='CheckedIn') process.exit(1)"
echo "CF-I08 analytics/reports/multi-hotel D1/API regression PASS"
